#!/usr/bin/env node
/**
 * derive-facts.js — агрегирует активные факты из life/<entity>/items.json
 * в один markdown-файл life/_derived/facts-active.md для индексации QMD.
 *
 * Зачем: summary.md покрывает ~32% фактов, остальные 68% (active, high-quality)
 * сейчас невидимы для гибридного поиска. Этот файл закрывает gap.
 *
 * Фильтр: status !== "superseded" (и pending — оставляем).
 * Формат: ## <entity> → ### <category> → bullet list с метаданными.
 *          Заголовки дают qmd естественные chunk-границы для BM25.
 */
import fs from "node:fs";
import path from "node:path";

const LIFE_ROOT = path.resolve(process.cwd(), "life");
const OUTPUT = path.join(LIFE_ROOT, "_derived", "facts-active.md");
const SKIP_DIRS = new Set(["_derived", "node_modules", ".git"]);

function walk(dir, out = []) {
  if (!fs.existsSync(dir)) return out;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (SKIP_DIRS.has(entry.name) || entry.name.startsWith(".")) continue;
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(p, out);
    else out.push(p);
  }
  return out;
}

const itemsFiles = walk(LIFE_ROOT).filter((p) => p.endsWith("items.json"));

const entities = [];
let totalActive = 0;
let totalSuperseded = 0;
let totalAll = 0;

for (const fp of itemsFiles) {
  let obj;
  try {
    obj = JSON.parse(fs.readFileSync(fp, "utf8"));
  } catch (e) {
    console.error(`[warn] failed to parse ${fp}: ${e.message}`);
    continue;
  }
  const facts = Array.isArray(obj.facts) ? obj.facts : [];
  const active = facts.filter((f) => f.status !== "superseded");
  const superseded = facts.length - active.length;

  totalAll += facts.length;
  totalActive += active.length;
  totalSuperseded += superseded;

  if (active.length === 0) continue;

  const entityRel = path
    .relative(LIFE_ROOT, path.dirname(fp))
    .replace(/\\/g, "/");

  entities.push({ entity: entityRel, facts: active });
}

entities.sort((a, b) => a.entity.localeCompare(b.entity));

function groupByCategory(facts) {
  const m = new Map();
  for (const f of facts) {
    const c = f.category || "context";
    if (!m.has(c)) m.set(c, []);
    m.get(c).push(f);
  }
  // Стабильный порядок категорий — для детерминированной генерации
  const order = [
    "milestone",
    "decision",
    "context",
    "status",
    "preference",
    "relationship",
    "correction",
  ];
  return [...m.entries()].sort(
    (a, b) =>
      (order.indexOf(a[0]) === -1 ? 99 : order.indexOf(a[0])) -
      (order.indexOf(b[0]) === -1 ? 99 : order.indexOf(b[0]))
  );
}

function factLine(f) {
  const text = String(f.fact || "").replace(/\s+/g, " ").trim();
  const conf =
    typeof f.confidence === "number" ? f.confidence.toFixed(1) : "?";
  const level = f.abstractionLevel || "?";
  const date = String(f.timestamp || f.source || "").slice(0, 10);
  const tags = Array.isArray(f.tags) && f.tags.length
    ? " " + f.tags.map((t) => `#${t}`).join(" ")
    : "";
  const rel = Array.isArray(f.relatedEntities) && f.relatedEntities.length
    ? ` ↔${f.relatedEntities.length}`
    : "";
  return `- ${text} _(conf=${conf}, ${level}, ${date}${rel})_${tags}`;
}

const now = new Date().toISOString();
let md = "";
md += `<!-- _Auto-generated by skills/engram/scripts/derive-facts.js at ${now} — DO NOT EDIT._ -->\n\n`;
md += `# Derived Active Facts\n\n`;
md += `> **Source:** \`life/**/items.json\` · **Filter:** \`status !== "superseded"\` · **Stats:** ${totalActive} active / ${totalSuperseded} superseded (skipped) / ${totalAll} total · **Entities:** ${entities.length}\n\n`;
md += `_Этот файл — производный слой между \`items.json\` (raw store) и \`summary.md\` (digest). Регенерируется после каждого \`memory-write\`. Цель: поднять recall QMD-поиска с ~32% (только summary) до ~100% (summary + этот файл)._\n\n---\n\n`;

for (const { entity, facts } of entities) {
  md += `## ${entity} (${facts.length})\n\n`;
  for (const [cat, list] of groupByCategory(facts)) {
    md += `### ${cat}\n\n`;
    for (const f of list) {
      md += factLine(f) + "\n";
    }
    md += "\n";
  }
}

fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
fs.writeFileSync(OUTPUT, md);

const sizeKB = (fs.statSync(OUTPUT).size / 1024).toFixed(1);
console.log(`✓ Wrote ${path.relative(process.cwd(), OUTPUT)}`);
console.log(
  `  Active: ${totalActive} | Superseded (skipped): ${totalSuperseded} | Entities: ${entities.length} | Size: ${sizeKB} KB`
);
