#!/usr/bin/env bun
import { randomUUID } from "node:crypto";
import { spawnSync } from "node:child_process";
import {
  closeSync,
  existsSync,
  fsyncSync,
  mkdirSync,
  openSync,
  readFileSync,
  renameSync,
  writeFileSync,
} from "node:fs";
import { dirname, isAbsolute, join, resolve } from "node:path";
import { parseArgs } from "node:util";
import { canonicalizeJcs, sha256Digest } from "../src/oll/handoff-v2.ts";

type JsonObject = Record<string, any>;

const { values } = parseArgs({
  args: process.argv.slice(2),
  options: {
    action: { type: "string", default: "plan" },
    "job-id": { type: "string" },
    workspace: { type: "string", default: "/opt/openclaw/workspace" },
    "state-root": { type: "string" },
    "backup-path": { type: "string" },
    "ack-scheduler": { type: "boolean", default: false },
    "ack-scheduler-rollback": { type: "boolean", default: false },
  },
  strict: true,
});

function required(name: "job-id" | "backup-path"): string {
  const value = values[name];
  if (typeof value !== "string" || !value.trim()) throw new Error(`--${name} is required`);
  return value.trim();
}

function atomicWrite(path: string, value: unknown): void {
  mkdirSync(dirname(path), { recursive: true, mode: 0o700 });
  const temporary = `${path}.tmp-${process.pid}-${randomUUID()}`;
  const descriptor = openSync(temporary, "wx", 0o600);
  try {
    writeFileSync(descriptor, `${JSON.stringify(value, null, 2)}\n`, "utf8");
    fsyncSync(descriptor);
  } finally { closeSync(descriptor); }
  renameSync(temporary, path);
}

function digest(value: unknown): `sha256:${string}` {
  return sha256Digest(canonicalizeJcs(value));
}

function openclaw(argv: string[], input?: string): string {
  const binary = process.env.ENGRAM_OPENCLAW || Bun.which("openclaw");
  if (!binary) throw new Error("openclaw binary is unavailable");
  const javascript = /\.(?:c|m)?js$/i.test(binary);
  const result = spawnSync(javascript ? process.execPath : binary, javascript ? [binary, ...argv] : argv, {
    encoding: "utf8",
    input,
    shell: false,
  });
  if (result.error || result.status !== 0) throw new Error(result.stderr || result.error?.message || `openclaw exited ${result.status}`);
  return result.stdout || "";
}

function liveJob(jobId: string): JsonObject {
  const value = JSON.parse(openclaw(["cron", "get", jobId]));
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("scheduler read-back is invalid");
  return value;
}

function buildScript(workspace: string): string {
  const command = `bun ${JSON.stringify(join(workspace, "skills", "engram", "scripts", "memory-observation-batch-worker.ts"))} --workspace ${JSON.stringify(workspace)}`;
  return `// Generated by install-memory-observation-batch-cron.ts.
const execution = await exec({
  command: ${JSON.stringify(command)},
  workdir: ${JSON.stringify(workspace)},
  yieldMs: 240000,
  timeoutSeconds: 300,
});
if (!execution || execution.status !== "completed" || !Number.isInteger(execution.exitCode)) {
  throw new Error("Engram batch exec did not return a completed exit status");
}
if (execution.exitCode !== 0) {
  const detail = typeof execution.aggregated === "string" && execution.aggregated.trim()
    ? execution.aggregated
    : JSON.stringify(execution);
  throw new Error("Engram batch worker exited " + execution.exitCode + ": " + detail.slice(-4000));
}
return { state: { workerResult: String(execution.aggregated ?? "") } };`;
}

function candidate(workspace: string): JsonObject {
  return {
    kind: "script",
    script: buildScript(workspace),
    timeoutSeconds: 300,
    toolBudget: 2,
    toolsAllow: ["exec"],
  };
}

function preserved(job: JsonObject): JsonObject {
  return {
    id: job.id,
    agentId: job.agentId,
    sessionKey: job.sessionKey,
    owner: job.owner,
    schedule: job.schedule,
    delivery: job.delivery,
    failureAlert: job.failureAlert,
    enabled: job.enabled,
  };
}

function plan(): JsonObject {
  const jobId = required("job-id");
  const workspace = resolve(String(values.workspace));
  if (!isAbsolute(workspace)) throw new Error("--workspace must be absolute");
  const current = liveJob(jobId);
  if (current.id !== jobId || current.enabled !== true || current.schedule?.kind !== "cron") {
    throw new Error("live scheduler identity, enabled state, or cron schedule drifted");
  }
  const next = candidate(workspace);
  return {
    schema: "engram.memory-batch-scheduler-rollout-plan.v1",
    jobId,
    workspace,
    preserved: preserved(current),
    currentPayloadRevision: digest(current.payload),
    candidatePayloadRevision: digest(next),
    candidatePayload: next,
    mutatesRuntime: false,
  };
}

function install(): JsonObject {
  if (values["ack-scheduler"] !== true) throw new Error("install requires --ack-scheduler");
  const rollout = plan();
  const current = liveJob(rollout.jobId);
  const stateRoot = resolve(String(values["state-root"] || join(rollout.workspace, "memory-state", "memory-observation", "scheduler-rollouts")));
  const backupPath = join(stateRoot, "backups", `${rollout.currentPayloadRevision.slice(7)}.json`);
  if (!existsSync(backupPath)) atomicWrite(backupPath, {
    schema: "engram.memory-batch-scheduler-backup.v1",
    jobId: rollout.jobId,
    payloadRevision: rollout.currentPayloadRevision,
    job: current,
    createdAt: new Date().toISOString(),
  });
  const next = rollout.candidatePayload;
  openclaw([
    "cron", "edit", rollout.jobId,
    "--script", "-",
    "--script-timeout-seconds", String(next.timeoutSeconds),
    "--script-tool-budget", String(next.toolBudget),
    "--tools", next.toolsAllow.join(","),
  ], next.script);
  const readBack = liveJob(rollout.jobId);
  if (digest(readBack.payload) !== rollout.candidatePayloadRevision) throw new Error("scheduler payload read-back mismatch");
  if (JSON.stringify(preserved(readBack)) !== JSON.stringify(rollout.preserved)) throw new Error("scheduler non-payload fields changed");
  const releasePath = join(stateRoot, "releases", `${rollout.candidatePayloadRevision.slice(7)}.json`);
  atomicWrite(releasePath, {
    schema: "engram.memory-batch-scheduler-release.v1",
    jobId: rollout.jobId,
    payloadRevision: rollout.candidatePayloadRevision,
    backupPath,
    readBackAt: new Date().toISOString(),
  });
  return { ...rollout, status: "installed", backupPath, releasePath };
}

function rollback(): JsonObject {
  if (values["ack-scheduler-rollback"] !== true) throw new Error("rollback requires --ack-scheduler-rollback");
  const jobId = required("job-id");
  const backupPath = resolve(required("backup-path"));
  const backup = JSON.parse(readFileSync(backupPath, "utf8"));
  if (backup?.schema !== "engram.memory-batch-scheduler-backup.v1" || backup.jobId !== jobId
    || backup.job?.payload?.kind !== "script") throw new Error("scheduler backup is invalid");
  const payload = backup.job.payload;
  openclaw([
    "cron", "edit", jobId,
    "--script", "-",
    "--script-timeout-seconds", String(payload.timeoutSeconds),
    "--script-tool-budget", String(payload.toolBudget),
    "--tools", (payload.toolsAllow || []).join(","),
  ], payload.script);
  const readBack = liveJob(jobId);
  if (digest(readBack.payload) !== backup.payloadRevision) throw new Error("scheduler rollback read-back mismatch");
  if (JSON.stringify(preserved(readBack)) !== JSON.stringify(preserved(backup.job))) throw new Error("scheduler rollback changed non-payload fields");
  return { schema: "engram.memory-batch-scheduler-rollback.v1", status: "rolled_back", jobId, backupPath, payloadRevision: backup.payloadRevision };
}

const action = String(values.action);
const result = action === "plan" ? plan()
  : action === "install" ? install()
    : action === "rollback" ? rollback()
      : action === "status" ? liveJob(required("job-id"))
        : (() => { throw new Error("--action must be plan, install, rollback, or status"); })();
process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
